### ISSUE TITLE
issues on my vim

### ISSUE THREAD

**Issue by Jzarecta** [nvie/vim-pyflakes#3]
Keep getting the following errors:

``` python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 84, in check
  File "/home/jza/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 253, in __init__
    self.handleChildren(tree)
  File "/home/jza/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 520, in handleChildren
    self.handleNode(node, tree)
  File "/home/jza/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 555, in handleNode
    handler(node)
  File "/home/jza/.vim/bundle/pyflakes-vim/ftplugin/python/pyflakes/pyflakes/checker.py", line 779, in CLASSDEF
    for keywordNode in node.keywords:
AttributeError: 'ClassDef' object has no attribute 'keywords'
```

**Comment by Jzarecta** [comment]
I seen to have fixed it thanks to a recomendation on launchpad, it seems to be a bug when the script doesnt recognize the Python version.
https://bugs.launchpad.net/pyflakes/+bug/1277606/comments/3
